import Head from "next/head";
import Terminal from "../components/Terminal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Connor Campbell</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-zinc-200">
        <div className="flex h-screen bg-zinc-800">
          <div className="m-auto flex flex-col">
            <div className="m-6 flex shrink  items-center gap-8">
              <div className="">
                <h1 className="text-4xl font-bold leading-8">
                  Connor <span className="text-indigo-400">Campbell</span>
                </h1>
                <br/>
                <h2 className="text-2xl font-bold leading-5">
                  Full Stack Developer
                </h2>
              </div>
              <img
                className="w-32 rounded-full md:w-64"
                src="/hastings.jpg"
                alt="Picture of the author"
              />
            </div>
            <div>
              <Terminal />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
