import React from "react";
import Head from "next/head";
import Terminal from "../components/Terminal";
import { AiOutlineArrowDown } from "react-icons/ai";
import Image from "next/image"
import StackChart from "~/components/StackChart";

export default function Home() {
    const [continueButton, setContinueButton] = React.useState(false);

    return (
        <>
            <Head>
                <title>Connor Campbell</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="text-zinc-200 bg-zinc-800">
                <div className="flex w-full">
                    <div className="flex flex-col m-auto bg-zinc-800" >
                        <div className="m-6 flex shrink  items-center gap-5">
                            <div className="">
                                <h1 className="md:text-5xl text-4xl font-bold leading-10">
                                    Connor Campbell
                                </h1>
                                <br />
                                <h2 className="font-bold text-3xl leading-6 text-indigo-400">
                                    Full Stack Developer
                                </h2>
                            </div>
                            <img
                                className="w-36 rounded-full md:w-64"
                                src="/hastings.jpg"
                                alt="Picture of the author"
                            />
                        </div>
                        <div>
                            <Terminal setContinueButton={setContinueButton} />
                        </div>
                        <div className="h-9">
                            <a href="#experience">
                                <div className={`flex flex-col items-center md:m-auto ${continueButton ? "animate-fade-in" : "hidden"} text-xl font-bold`}>
                                    <div>Continue</div>
                                    <div>
                                        <AiOutlineArrowDown />
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div id="experience" className="aspect-[960/200] w-full bg-no-repeat bg-top bg-cover" style={{ backgroundImage: "url('/waves.svg')" }}>
                    <div className="md:h-40 h-32 w-screen md:w-96" />
                    <div className="flex h-screen w-screen text-zinc-700">
                        <div className="flex flex-col m-auto">
                            <div className="m-6 flex-col items-center">
                                <div className="text-4xl text-zinc-700 font-bold m-4 text-center">Developer Experience</div>
                                <StackChart />
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
